### PR TITLE
profiles: add go-1.5.3 to accepted keywords

### PR DESCRIPTION
**Pull request by crawford**
This ought to be interesting. Let's hold off on merging this until the Alpha is cut.

### CODE REVIEW

**Comment by glevand** [comment]
Got to do it sometime...

**Comment by marineam** [comment]
Why here instead of the ebuild?

**Comment by crawford** [comment]
:shrug: I forgot dev-lang/go was in the overlay. Let me update the keywords instead.

**Comment by marineam** [comment]
k, go ahead and prune old line in keywords while you are at it.

**Comment by crawford** [comment]
Pruned.

**Comment by marineam** [comment]
LGTM

**Pull request merged**
