### PR TITLE
Revert "dev-lang/spidermonkey: Better fix for CONFIG_ARM64_VA_BITS_48"

### PR DESCRIPTION
**Pull request by crawford**
Reverts coreos/coreos-overlay#2228

This was causing failures with fleet, of all things...

```
Oct 19 23:29:19 localhost polkitd[1166]: /usr/share/polkit-1/rules.d/98-fleet-org.freedesktop.systemd1.rules:2: TypeError: action.id is null
Oct 19 23:29:19 localhost polkitd[1166]: Error evaluating authorization rules
Oct 19 23:29:19 localhost fleetd[1882]: ERROR manager.go:140: Failed to trigger systemd unit hello.service stop: Permission denied
Oct 19 23:29:19 localhost fleetd[1882]: INFO manager.go:259: Removing systemd unit hello.service
Oct 19 23:29:19 localhost polkitd[1166]: /usr/share/polkit-1/rules.d/98-fleet-org.freedesktop.systemd1.rules:2: TypeError: action.id is null
Oct 19 23:29:19 localhost polkitd[1166]: Error evaluating authorization rules
Oct 19 23:29:19 localhost fleetd[1882]: INFO manager.go:246: Writing systemd unit hello.service (37b)
Oct 19 23:29:19 localhost polkitd[1166]: /usr/share/polkit-1/rules.d/98-fleet-org.freedesktop.systemd1.rules:2: TypeError: action.id is null
Oct 19 23:29:19 localhost polkitd[1166]: Error evaluating authorization rules
Oct 19 23:29:19 localhost fleetd[1882]: INFO reconcile.go:330: AgentReconciler completed task: type=UnloadUnit job=hello.service reason="unit loaded but hash differs to expected"
Oct 19 23:29:19 localhost fleetd[1882]: INFO reconcile.go:332: AgentReconciler task failed: type=LoadUnit job=hello.service reason="unit scheduled here but not loaded" err=Permission denied
```

### CODE REVIEW

**Comment by garygrebus** [comment]
That's very odd.  We found fleet unusable without that patch, which fixed exactly the problem you show above  "TypeError: action.id is null".   Are you sure your testing procedure was correct?

**Comment by crawford** [comment]
Yeah, it's our automated test framework (kola) that was seeing the failures on AMD64. Did the patch swap the failure from one architecture to the other?

**Comment by garygrebus** [comment]
OK now I'm remembering this more clearly ...  

What we saw on ARM64 without the patch to spidermonkey was polkitd crashing with the "translation fault" problem.   Applying the patch fixed that problem, so polkitd was able to get far enough to service the request from fleet.   At that point it was reporting the "TypeError: action.id is null" problem,  the same results you show above.

At that point, I did a "build_packages",  motivated by this thread: https://bugzilla.redhat.com/show_bug.cgi?id=1242326 , which said:
"Note : mozjs1.8.5 is a bit different. Because the old mozjs has pre-generated js strings in C code which will be mapped to memory by dynamic linker, so changing heap allocation doesn't help. But the patch for mozjs1.8.5 modifies the tag pointer data structure which is a part of JSAPI, so all the packages depending on mozjs1.8.5 need to be re-built if the patch is used."

At that point the polkitd problem was fixed, and fleet started working.  Sorry... I should have mentioned that.

I did a test build on AMD64 with the patch, and verified pokitd started up.  I don't think I tried fleet on AMD64 at that point.

**Pull request merged**
