### PR TITLE
coreos-overlay: Remove cmake dependencies

### PR DESCRIPTION
**Pull request by glevand**
Commit 60d47e7359d11751b05ddf010a97f0d800c9f9bf (dev-util/bsdiff: Change suffix sort to sais-lite) removed the dependencies on libdivsufsort and cmake.  Cleanup any remaining files or DEPENDS.

### CODE REVIEW

**Comment by marineam** [comment]
dev-libs/libdivsufsort can be dropped but @crawford is in the middle of experimenting with rust, and a couple of rust libraries use cmake. We aren't sure what the long term plan is going to look like but until that is sorted out lets leave cmake in the SDK. At least is isn't in the dependency tree for boards now.

**Comment by glevand** [comment]
Just merged patch for removal of libdivsufsort.

**Comment by marineam** [comment]
Great, thanks!

**Comment by marineam** [comment]
rust is gone so the removal of cmake can go forward now.

**Comment by glevand** [comment]
I created a new PR to finish this: https://github.com/coreos/coreos-overlay/pull/1495 (hard-host-depends: Remove unused dev-util/cmake)

**Pull request merged**
