### PR TITLE
sys-apps/systemd: nspawn Map seccomp filters to caps

### PR DESCRIPTION
**Pull request by jayofdoom**
http://cgit.freedesktop.org/systemd/systemd/commit/?id=9a71b1122c6e49dd9227f82b2f53837c7ea13019

Fixes coreos/bugs#293

### CODE REVIEW

**Comment by crawford** [comment]
You'll also need to bump the file name to sys-apps/systemd/systemd-219-r2.ebuild

**Comment by crawford** [comment]
Can you also add this to the 218 ebuild? We aren't currently shipping 219.

**Comment by crawford** [comment]
It builds... LGTM!

**Comment by marineam** [comment]
[LGTM](http://www.lgtm.in/i/ier1)

**Pull request merged**
