### PR TITLE
sys-apps/systemd: add Xen and CCISS fixes

### PR DESCRIPTION
**Pull request by crawford**

### CODE REVIEW

**Comment by mischief** [comment]
lgtm

**Comment by marineam** [comment]
LGTM but we need to check on cciss too https://github.com/coreos/systemd/pull/9#issuecomment-110249839

**Comment by crawford** [comment]
Updated to include CCISS fix.

**Comment by marineam** [comment]
LGTM, can you poke upstream too or should I?

**Comment by crawford** [comment]
I submitted a PR. I don't know if you want to make any more fuss about this though.

**Pull request merged**
