### PR TITLE
app-emulation/rkt: bump version 0.9.0 -> 0.11.0

### PR DESCRIPTION
**Pull request by steveeJ**
Fixes https://github.com/coreos/bugs/issues/988

### CODE REVIEW

**Comment by jonboulle** [comment]
LGTM, trusting @steveeJ has tested it :-)

**Comment by mischief** [comment]
does this require systemd v227 to work properly?

**Comment by steveeJ** [comment]
No, should work with the specified dependencies. Did you run into any trouble or are you just double-checking?

**Comment by mischief** [comment]
@steveeJ: @iaguis requested systemd v227 specifically for rkt here: https://github.com/coreos/bugs/issues/979, but @crawford seemed reluctant to update systemd right now.

**Comment by jonboulle** [comment]
@mischief in rkt we consider the dependency in the inverse:
https://github.com/coreos/rkt/issues/1759

**Comment by steveeJ** [comment]
@mischief We want a newer systemd in the CoreOS image eventually. I'm not sure what would happen if the ebuild supplied a different CoreOS image than the one expected in the stage1 build system: https://github.com/coreos/rkt/blob/v0.11.0/stage1/usr_from_coreos/coreos-common.mk#L12.

**Comment by marineam** [comment]
LGTM

**Pull request merged**
