### PR TITLE
app-admin/mayday: use current master for some new stuff

### PR DESCRIPTION
**Pull request by mischief**

### CODE REVIEW

**Comment by crawford** [comment]
Why? We already have cros_workon.

**Comment by mischief** [comment]
to bring in new changes into the image.

**Comment by crawford** [comment]
If you use the live ebuild, it is going to use the code in tree. If you build 0.1.0, it's going to use that tag. I don't see how this will end up ever building 85f8b48da25fd6e3c36a9aa1f7d90c19078777ab.

**Comment by mischief** [comment]
mayday is in manifest - it will build 85f8b48da25fd6e3c36a9aa1f7d90c19078777ab for =app-admin/mayday-0.1.0-r1.

**Comment by crawford** [comment]
Oh, I didn't see that symlink. I see now.

Why are you including code that isn't a part of a release?

**Comment by mischief** [comment]
i'll see about a release then. cc @brianredbeard

**Pull request closed without merging**
