### PR TITLE
Fix efitools build failure

### PR DESCRIPTION
**Pull request by mjg59**
A dependency in the efitools Makefile was incorrect, resulting in it failing
on systems with large numbers of cores.

### CODE REVIEW

**Comment by marineam** [comment]
Woo, thanks. This was hurting a couple automated build jobs too over the weekend.

Where is the git repo you are generating these snapshots from?

**Comment by glevand** [comment]
Seems to build OK now.  Thanks.

**Comment by marineam** [comment]
Oops, forgot this hadn't merged yet.

**Comment by mjg59** [comment]
https://github.com/mjg59/efitools

**Comment by marineam** [comment]
@mjg59 Thanks. Somehow github search failed to find that earlier. Go figure.

**Pull request merged**
