### PR TITLE
sys-kernel/*: add qede module

### PR DESCRIPTION
**Pull request by ajeddeloh**
As per user request, add CONFIG_QEDE and its dependency, CONFIG_QED.

### CODE REVIEW

**Comment by ajeddeloh** [comment]
https://jenkins-container-linux.apps.ci.centos.org/job/os/job/manifest/458/console

**Comment by pijany** [comment]
thanks mate. after merge I will test and let you know.

**Comment by ajeddeloh** [comment]
@pijany Here's the image built by CI, can you test it and verify it works?

https://builds.developer.core-os.net/boards/amd64-usr/2345.0.0+jenkins3-master-local-460/coreos_production_image.bin.bz2

If you need a different image we create, you can change out the last bit to match the names of the artifacts we publish for releases.

I'll hold merging until you confirm it works.

**Comment by pijany** [comment]
> @pijany Here's the image built by CI, can you test it and verify it works?
> 
> https://builds.developer.core-os.net/boards/amd64-usr/2345.0.0+jenkins3-master-local-460/coreos_production_image.bin.bz2
> 
> If you need a different image we create, you can change out the last bit to match the names of the artifacts we publish for releases.
> 
> I'll hold merging until you confirm it works.

@ajeddeloh  we are using coreos in openstack ironic, can you build image for pxe (vmlinuz and initramfs).
Thanks.

**Comment by ajeddeloh** [comment]
http://builds.developer.core-os.net/boards/amd64-usr/2345.0.0+jenkins3-master-local-471/coreos_production_pxe.vmlinuz

http://builds.developer.core-os.net/boards/amd64-usr/2345.0.0+jenkins3-master-local-471/coreos_production_pxe.cpio.gz

The initial build failed do to a build bug hence the missing images, but the rebased one succeeded. Try those.

**Comment by ajeddeloh** [comment]
@pijany ping, would be good to merge this before the holidays

**Comment by pijany** [comment]
@ajeddeloh  sorry for lack of response due to holidays we go frez so I wan't able to test it.
Link to cpio file doesn't work, can you check this for me.
http://builds.developer.core-os.net/boards/amd64-usr/2345.0.0+jenkins3-master-local-471/coreos_production_pxe.cpio.gz

Thanks.

**Comment by ajeddeloh** [comment]
Oh, my bad, typo'd it. Should be http://builds.developer.core-os.net/boards/amd64-usr/2345.0.0+jenkins3-master-local-471/coreos_production_pxe_image.cpio.gz (forgot `_image`)

**Comment by pijany** [comment]
@ajeddeloh all worked perfect :). Host boot with qlogic card and obtain ip 👍

**Comment by bgilbert** [comment]
https://jenkins-container-linux.apps.ci.centos.org/job/os/job/manifest/518/cldsv/

**Pull request merged**
