### PR TITLE
app-admin/kubelet: update with better defaults

### PR DESCRIPTION
**Pull request by crawford**
KUBELET_DEFAULT_OPTS is used instead of individual environment variables
and flags in preparation for kubelet accepting environment variables in
the future. We don't want to collide with their flags, so we will just
convert our flag string to a series of environment variables when the
time comes.

### CODE REVIEW

**Comment by marineam** [comment]
I don't follow why early docker is a concern. Does the dependency actually fix a correctness issue or are you just favoring a more explicit serialized dependency chain?

**Comment by crawford** [comment]
Hmmm, I'm not sure why, but I thought that those dependencies were required. I do not believe they are.

**Comment by marineam** [comment]
I suppose if it works without and we leave them out, it'll be one less thing to think about when rkt support happens.

**Comment by marineam** [comment]
If you are going to put all the args together just drop the var and add them to the start command. At that point a dropin setting the env var would be just as repetitive as redefining the whole start command.

**Comment by crawford** [comment]
But then the user wouldn't easily be able to append onto the command line.

**Comment by marineam** [comment]
The user cannot append now, they can only replace the variable in one go

**Comment by crawford** [comment]
Sorry. There is another variable (`KUBELET_OPTS`) that the user can use. I could add `Environment=KUBELET_OPTS=` to make it more obvious.

**Comment by marineam** [comment]
Ah, well KUBELET_DEFAULT_OPTS is still pointless

**Comment by marineam** [comment]
LGTM

**Pull request merged**
