### PR TITLE
Enabled epoll for libmicrohttpd and systemd-journal-remote

### PR DESCRIPTION
**Pull request by kayrus**
@mischief @marineam @crawford 

resolves https://github.com/coreos/bugs/issues/919

### CODE REVIEW

**Comment by kayrus** [comment]
updated with ssl useflag. otherwise https doesn't work.

**Comment by kayrus** [comment]
I've noticed that ssl was turned off for systemd too. We have to enable ssl for security. https://github.com/coreos/coreos-overlay/commit/ea0bcc6a80a064e386accbf4ff290737bedac2a4

**Comment by marineam** [comment]
Turning off ssl was a deliberate choice to avoid shipping yet another ssl implementation requiring security updates. (gnutls)

If we start shipping gnutls I would favor migrating away from openssl where possible.

Let's leave ssl out of this PR, I want to review the state of things first.

**Comment by kayrus** [comment]
Left only epoll, as for ssl - I've created new ticket: https://github.com/coreos/bugs/issues/927

**Comment by marineam** [comment]
LGTM

**Pull request merged**
