### PR TITLE
app-emulation/wa-linux-agent: enable base64 decoding of userdata

### PR DESCRIPTION
**Pull request by mischief**
fixes coreos/bugs#1463

### CODE REVIEW

**Comment by vcaputo** [comment]
lgtm

**Comment by crawford** [comment]
Verified the fix. LGTM.

@szarkos refresh my memory, has the wire endpoint always returned CustomData encoded as Base64?

**Comment by szarkos** [comment]
Yes, it needs to be base64-encoded when sent to our APIs, and it's delivered to the VM as-is with the other configuration data in the ovf-env.xml file.

**Comment by crawford** [comment]
@szarkos gotcha. So the xplat-cli is doing the encoding for us.

**Pull request merged**
