### PR TITLE
sys-kernel/coreos-modules: enable ENA_ETHERNET

### PR DESCRIPTION
**Pull request by euank**
This change is part 1 of what will be a little more involved of a change for ENA support.

After making this change, I verified that an AMI built from this change launches and functions.

However, using AWS's [provided guide](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking-ena.html#test-enhanced-networking-ena), I verified the instance did not use the ENA module.

This is because the AMI must be registered with an attribute to let EC2 know that there's ENA support mixed in, but our AMI registration scripts don't currently do that.

Reusing the same snapshot, but registering it with a couple additional flags did get me an AMI where the ENA driver was used and networking worked fine.

```shell
$ aws ec2 register-image  --name CoreOS-master-1269-00-13-hvm-ena --description 'CoreOS master 1269-00-13 (HVM,ENA)' --architecture x86_64 --virtualization-type hvm --root-device-name /dev/xvda --block-device-mappings '[{"DeviceName":"/dev/xvda","Ebs":{"SnapshotId": "$snapshotID"}}, {"DeviceName":"/dev/xvdb","VirtualName": "ephemeral0"}]' --ena-support --sriov-net-support=simple
# notice: --ena-support --sriov-net-support=simple
```

This change, even without the other script changes, has a little value because a user can in theory snapshot and modify the image to create an AMI with ena-support, but it's not a great process.

cc @crawford

### CODE REVIEW

**Comment by marineam** [comment]
The revision (e.g. renaming to `coreos-modules-4.9.0-r1.ebuild`) needs to be bumped for both coreos-modules and coreos-kernel to reflect the config update.

**Comment by euank** [comment]
Thanks for the reminder, done

**Comment by zihaoyu** [comment]
@euank @marineam @crawford Are there separate AMIs with ENA enabled? I just launched from latest `CoreOS-stable-1298.5.0-hvm (ami-fd92109d)` and it was not using `ena` driver. 

```
core@ip-10-72-34-111 ~ $ ethtool -i eth0
driver: vif
version:
firmware-version:
bus-info: vif-0
supports-statistics: yes
supports-test: no
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: no
```

Once I stopped the instance and changed instance attribute to have `ena-support`, the driver was updated.

```
$ aws --region us-west-2 ec2 modify-instance-attribute --instance-id i-0e5da615dc83a8d50 --ena-support
```

```
core@ip-10-72-34-111 ~ $ ethtool -i eth0
driver: ena
version: 1.0.2
firmware-version:
bus-info: 0000:00:03.0
supports-statistics: yes
supports-test: no
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: no
```

Also, the latest version of `ena` module is `1.1.3`, which I manually compiled and installed on another instance by following [the guide](https://coreos.com/os/docs/latest/kernel-modules.html). But I understand to upgrade the module we need the upstream to upgrade first.

```
# latest version
core@ip-10-72-22-99 ~ $ modinfo ena
filename:       /lib/modules/4.9.9-coreos-r1/kernel/drivers/net/ethernet/amazon/ena/ena.ko
version:        1.1.3
license:        GPL
description:    Elastic Network Adapter (ENA)
author:         Amazon.com, Inc. or its affiliates
srcversion:     95D68BE3C0E363A5CDA8E13
alias:          pci:v00001D0Fd0000EC21sv*sd*bc*sc*i*
alias:          pci:v00001D0Fd0000EC20sv*sd*bc*sc*i*
alias:          pci:v00001D0Fd00001EC2sv*sd*bc*sc*i*
alias:          pci:v00001D0Fd00000EC2sv*sd*bc*sc*i*
depends:
vermagic:       4.9.9-coreos-r1 SMP mod_unload
parm:           debug:Debug level (0=none,...,16=all) (int)
```

```
# stock version
core@ip-10-72-34-111 ~ $ modinfo ena
filename:       /lib/modules/4.9.9-coreos-r1/kernel/drivers/net/ethernet/amazon/ena/ena.ko
version:        1.0.2
license:        GPL
description:    Elastic Network Adapter (ENA)
author:         Amazon.com, Inc. or its affiliates
srcversion:     0ADEBA934369F8D450E5CE4
alias:          pci:v00001D0Fd0000EC21sv*sd*bc*sc*i*
alias:          pci:v00001D0Fd0000EC20sv*sd*bc*sc*i*
alias:          pci:v00001D0Fd00001EC2sv*sd*bc*sc*i*
alias:          pci:v00001D0Fd00000EC2sv*sd*bc*sc*i*
depends:
intree:         Y
vermagic:       4.9.9-coreos-r1 SMP mod_unload
parm:           debug:Debug level (0=none,...,16=all) (int)
```

**Comment by crawford** [comment]
@zihaoyu I filed a bug - https://github.com/coreos/bugs/issues/1853.

**Pull request merged**
