### PR TITLE
app-admin/fleet: remove dependency on etcd

### PR DESCRIPTION
**Pull request by crawford**
We have to think about this one. We've done a pretty good job telling people to explicitly start etcd and fleet from their cloud-configs, but this will still break backwards-compatibility.

### CODE REVIEW

**Comment by philips** [comment]
It seems OK to me.

**Comment by marineam** [comment]
Re: c9b38cd21e8d441ce24ed0f6df1bdbf79f978e49 you should keep the after rule and include etcd2, just drop the wants.

We will need to call this one out loudly in the change log as anyone who is used to starting fleet but not etcd will be surprised by this. Fortunately we've always listed both in our examples as far as I know.

**Comment by crawford** [comment]
Updated.

**Comment by marineam** [comment]
@crawford need to add etcd2.service

**Comment by crawford** [comment]
;_; Too much context switching.

**Comment by marineam** [comment]
[LGTM](http://www.lgtm.in/i/M8YNeuxoq)

**Comment by crawford** [comment]
Holding off until the Alpha is built.

**Pull request merged**
