### PR TITLE
sys-kernel/coreos-*: bump to v4.11

### PR DESCRIPTION
**Pull request by bgilbert**
The new patch series is in https://github.com/coreos/linux/pull/55.

Config changes:

- The refreshed Secure Boot patches now use LOCK_DOWN_KERNEL and EFI_SECURE_BOOT_LOCK_DOWN instead of EFI_SECURE_BOOT_SIG_ENFORCE.
- KPROBE_EVENT and UPROBE_EVENT were pluralized in coreos/linux@6b0b7551428e4caae1e2c023a529465a9a9ae2d4.
- DEBUG_SET_MODULE_RONX was renamed in coreos/linux@0f5bf6d0afe4be6e1391908ff2d6dc9730e91550, but as of coreos/linux@ad21fc4faa2a1f919bac1073b885df9310dbc581 it's mandatory on both supported arches. Dropped.
- VMXNET3 conflicts with ARM64_64K_PAGES as of coreos/linux@fbdf0e28d061708cf18ba0f8e0db5360dc9a15b9, and likely doesn't make sense on ARM. Moved to amd64.
- TIMER_STATS was dropped in coreos/linux@dfb4357da6ddbdf57d583ba64361c9d792b0e0b1.
- CPU_FREQ_STAT_DETAILS was dropped in coreos/linux@801e0f378fe7d53f87246037bf40567277275418.

### CODE REVIEW

**Comment by drcrallen** [comment]
This broke some modules that were using `LL_FLUSH_FAILED` and `LL_FLUSH_BUSY`, which seemed to have been removed from http://elixir.free-electrons.com/linux/v4.11/source/include/net/busy_poll.h as per https://github.com/amzn/amzn-drivers/issues/14

**Comment by bgilbert** [comment]
@drcrallen Does the in-kernel ENA driver not suit your needs?  It is enabled in our kernel configs.

**Comment by drcrallen** [comment]
Unsure, I'll check it out

**Comment by drcrallen** [comment]
```
core@ip-172-19-68-119 ~ $ sudo ethtool -i eth0
driver: vif
version:
firmware-version:
bus-info: vif-0
supports-statistics: yes
supports-test: no
supports-eeprom-access: no
supports-register-dump: no
supports-priv-flags: no
```
it is the vif driver not the amzn ena driver

this is what gets pulled in a x1.32xlarge 

```
core@ip-172-19-68-119 ~ $ lsmod
Module                  Size  Used by
i2c_piix4              24576  0
i2c_core               49152  1 i2c_piix4
mousedev               20480  0
sb_edac                24576  0
edac_core              40960  1 sb_edac
evdev                  24576  2
psmouse                28672  0
button                 16384  0
sch_fq_codel           20480  1
xenfs                  16384  1
xen_privcmd            16384  1 xenfs
nls_ascii              16384  1
nls_cp437              20480  1
vfat                   20480  1
fat                    65536  1 vfat
ext4                  516096  3
crc16                  16384  1 ext4
jbd2                   90112  1 ext4
fscrypto               24576  1 ext4
mbcache                16384  1 ext4
dm_verity              20480  1
dm_bufio               24576  1 dm_verity
xen_blkfront           40960  5
xen_netfront           28672  0
crc32c_intel           20480  0
ata_piix               36864  0
aesni_intel           147456  0
aes_x86_64             20480  1 aesni_intel
crypto_simd            16384  1 aesni_intel
libata                200704  1 ata_piix
cryptd                 20480  2 crypto_simd,aesni_intel
glue_helper            16384  1 aesni_intel
scsi_mod              192512  1 libata
dm_mirror              24576  0
dm_region_hash         16384  1 dm_mirror
dm_log                 20480  2 dm_mirror,dm_region_hash
dm_mod                 94208  6 dm_mirror,dm_log,dm_bufio,dm_verity
```

**Comment by drcrallen** [comment]
```
core@ip-172-19-68-119 ~ $ sudo modinfo ena
filename:       /lib/modules/4.11.0-coreos/kernel/drivers/net/ethernet/amazon/ena/ena.ko
version:        1.1.2
license:        GPL
description:    Elastic Network Adapter (ENA)
author:         Amazon.com, Inc. or its affiliates
srcversion:     108100869D86D6F6E1396A3
alias:          pci:v00001D0Fd0000EC21sv*sd*bc*sc*i*
alias:          pci:v00001D0Fd0000EC20sv*sd*bc*sc*i*
alias:          pci:v00001D0Fd00001EC2sv*sd*bc*sc*i*
alias:          pci:v00001D0Fd00000EC2sv*sd*bc*sc*i*
depends:
intree:         Y
vermagic:       4.11.0-coreos SMP mod_unload
parm:           debug:Debug level (0=none,...,16=all) (int)
```
exists but vif gets loaded instead. Not sure why. Will dig more.

`sudo modprobe ena` succeeds so I think my concern is more procedural rather than "oh crap it can't compile". Thanks!

**Comment by netanelbelgazal** [comment]
@drcrallen, 
It looks like your AMI doesn't have enhanced-networking attribute enabled.
To enable it please refer to:
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enhanced-networking-ena.html#enable-enhanced-networking-ena-AL

**Pull request merged**
