### PR TITLE
coreos-base/oem-*: add config for etcd2

### PR DESCRIPTION
**Pull request by crawford**

### CODE REVIEW

**Comment by marineam** [comment]
LGTM

**Comment by crawford** [comment]
Holding off until the Alpha is built.

**Comment by philips** [comment]
@crawford So we are aiming for next week? Let me know how I can help with docs and blog.

**Comment by crawford** [comment]
@philips yes, we are shooting for a release next week. I'm going to do a build tonight so we can start testing ASAP.

**Pull request merged**
