### PR TITLE
Merge pull request #2215 from crawford/docker

### PR DESCRIPTION
**Pull request by joeatwork**
app-emulation/docker: revert to 1.11.2

These changes are unchanged from #2215

### CODE REVIEW

**Comment by crawford** [comment]
Can you cherry-pick the actual commit instead of the merge?

**Comment by joeatwork** [comment]
Will do!

**Comment by joeatwork** [comment]
Done - PTAL

**Comment by crawford** [comment]
Looks good. Hold off on merging until we tag the Alpha.

**Comment by joeatwork** [comment]
Discussed IRL - merging now (Thanks @crawford !)

**Pull request merged**
