### PR TITLE
Include PAM support

### PR DESCRIPTION
**Pull request by mjg59**

### CODE REVIEW

**Comment by crawford** [comment]
Why is PAM in coreos-overlay and not portage-stable?

**Comment by mjg59** [comment]
Because we need to patch it to have the appropriate behaviour around locked
accounts and to install config in the right place

**Comment by crawford** [comment]
Can you break that into two commits then - one pulling down upstream and the other making changes?

**Comment by crawford** [comment]
(or is that what I am looking at)

**Comment by mischief** [comment]
retest this please

**Comment by mjg59** [comment]
Ok, this one creates /etc/environment in tmpfiles and has the update/modification split up.

**Comment by marineam** [comment]
LGTM

**Pull request merged**
