### PR TITLE
app-emulation/docker: Fix go-1.5 and arm64 builds

### PR DESCRIPTION
**Pull request by glevand**
Apply the fix from upstream docker.
https://github.com/docker/docker/pull/15404

Fixes build errors like these:

  devmapper_wrapper.go: Cdeps.device undefined (type *C.struct_dm_deps has no field or method device)

### CODE REVIEW

**Comment by marineam** [comment]
We've already started a git based bugfix branch so this fix can go there: https://github.com/coreos/docker/tree/coreos-1.7.1

**Comment by glevand** [comment]
Created PR https://github.com/coreos/docker/pull/2

**Comment by glevand** [comment]
@marineam Changed this to just update the CROS_WORKON_COMMIT to pickup the go-1.5 and the arm64 fixes.

Depends on https://github.com/coreos/docker/pull/2 and https://github.com/coreos/docker/pull/3, which have now been merged.

**Comment by marineam** [comment]
Please bump the revision in the 1.7.1 symlink as well

**Comment by glevand** [comment]
Updated symlink.  Thanks for checking.

**Comment by marineam** [comment]
LGTM

**Pull request merged**
