### PR TITLE
app-admin/mayday: bump to v1.0.0

### PR DESCRIPTION
**Pull request by mischief**

### CODE REVIEW

**Comment by marineam** [comment]
LGTM

**Comment by mischief** [comment]
waiting for @tschuy

**Comment by tschuy** [comment]
it needs its `default.json` file to be copied to `/usr/share/mayday/default.json` (we moved the command/dir listing out of the binary).

**Comment by mischief** [comment]
ok, copied to `/usr/share/mayday/default.json`. PTAL.

**Comment by tschuy** [comment]
:+1:

**Pull request merged**
