### PR TITLE
arm64 kconfig sync

### PR DESCRIPTION
**Pull request by mischief**
@marineam what were the other modules groups you mentioned should be sync'd?

### CODE REVIEW

**Comment by marineam** [comment]
Filesystems, dm/md, crypto, and so on. Just diff the two configs and skim for options that aren't arch specific. Even USB devices could get coppied since those aren't tied to the specific platform.

**Comment by marineam** [comment]
In the end the two configs should be pretty similar

**Comment by damoon** [comment]
maybe https://github.com/coreos/bugs/issues/1500 (enable CONFIG_DNS_RESOLVER=y) could be synced too?

**Comment by glevand** [comment]
What you have so far looks fine.  My original file was based on the upstream arm64 defconfig.

**Comment by marineam** [comment]
LGTM, we can do more in another PR

**Pull request merged**
