### PR TITLE
CFS throttling fixes for kernel 4.19.81

### PR DESCRIPTION
**Pull request by jhohertz**
Based on coreos/coreos-overlay#3787

Not sure if you want to merge them together, or for me to increment revision on this specific PR. Happy to do either.

### CODE REVIEW

**Comment by bgilbert** [comment]
Please do increment the revision, since #3787 has merged.  Once you get this updated we'll run it through CI.

Per https://github.com/coreos/bugs/issues/2623#issuecomment-549544785 do we need torvalds/linux@512ac999 also?

**Comment by jhohertz** [comment]
Per the other commit, I see it in the parent branch history coreos/linux@512ac99 so I think it's already there.

I'll bump the revision shortly.

**Comment by jhohertz** [comment]
I think it's all here now. Running a local build now, will let you know if I see any issues.

**Comment by bgilbert** [comment]
https://jenkins-container-linux.apps.ci.centos.org/job/os/job/manifest/394/cldsv/

**Comment by bgilbert** [comment]
Patches merged in https://github.com/coreos/linux/pull/364.

**Comment by bgilbert** [comment]
Thanks for the PR!  :tada:

**Comment by jhohertz** [comment]
You're welcome!

**Pull request merged**
