### PR TITLE
sys-kernel/coreos-{sources,kernel}: update to 4.6.3

### PR DESCRIPTION
**Pull request by mischief**

### CODE REVIEW

**Comment by marineam** [comment]
LGTM

**Comment by marineam** [comment]
OH,!! manifest!!

**Comment by marineam** [comment]
(so not LGTM yet)

**Comment by mischief** [comment]
#$!%

**Comment by marineam** [comment]
[LGTM](http://lgtm.in/i/aR2Kx3d5q)

**Pull request merged**
