### PR TITLE
pass /etc/machine-id from host to kubelet

### PR DESCRIPTION
**Pull request by databus23**
Otherwise kubelet/cadvisor picks up whatever is shipped in the container image, which results in all nodes reporting the same value for `status.nodeInfo.machineID`

### CODE REVIEW

**Comment by lucab** [comment]
This looks fine to me, but I'd like to have @euank and @aaronlevy check for possible side-effects at the k8s level before merging this.

**Comment by lucab** [comment]
@databus23 thanks for the patch, this is mostly ready to get in. Can you please also bump the ebuild version?

**Comment by databus23** [comment]
@dm0- renamed ebuild file as requested

**Comment by euank** [comment]
Thanks again!

**Pull request merged**
