### PR TITLE
Transmission

### PR DESCRIPTION
**Pull request by polvi**
Adds transmission ebuild, and patches it to require a reduced set of libraries.

### CODE REVIEW

**Comment by crawford** [comment]
Can you shorten that second commit message? Otherwise, LGTM.

**Comment by brianredbeard** [comment]
I see that the `IUSE` is set for both QT4 and GTK. Just wanted to confirm that it's not building the corresponding GUI packages.

**Comment by crawford** [comment]
`IUSE` is just the list of options. They are only set if they begin with `+`.

**Comment by polvi** [comment]
rebased and fixed message, lets see if I can get this PR to update

**Comment by polvi** [comment]
got it!

**Pull request merged**
