### PR TITLE
systemd: add UseNTP DHCP option for network configs

### PR DESCRIPTION
**Pull request by marineam**
Updates both 218 and 219, for now only 218 has been tested.

### CODE REVIEW

**Comment by crawford** [comment]
Can you add the patch to the 219 ebuild as well?

**Comment by marineam** [comment]
@crawford fixed, split the 219 ebuild copy from the patch commit too

**Comment by marineam** [comment]
@crawford updated again, adding a second patch to allow timesyncd to start in virtual machines. Both patches are upstream.

**Comment by crawford** [comment]
LGTM

**Pull request merged**
