### PR TITLE
coreos-sources: add patch minimizing allocation in ovl_copy_xattr

### PR DESCRIPTION
**Pull request by vcaputo**
Fixes https://github.com/coreos/bugs/issues/489

### CODE REVIEW

**Comment by marineam** [comment]
LGTM

**Comment by pmoust** [comment]
Has this been sent to maintainers for review?

**Comment by vcaputo** [comment]
@pmoust I've notified Miklos about this issue/patch.  We'd like this patch to percolate upstream, but our priority is fixing coreos where overlayfs is so fundamental to its practical use.

**Comment by pmoust** [comment]
@vcaputo thanks for your work.

Sorry for hijacking the thread, how long after a patch is pushed in your repos should we expect it to hit the Alpha channel? I tried checking the docs and I did not manage to grasp that piece of info.

**Comment by mischief** [comment]
@pmoust it will be in the next alpha which should go out tomorrow.

**Comment by klausenbusk** [comment]
> @pmoust it will be in the next alpha which should go out tomorrow.

and how long before it hit stable? 1-2 months?

**Comment by vcaputo** [comment]
@klausenbusk we'll likely be back-porting to get this into the stable channel sooner, just needs to simmer in alpha a bit first.

**Comment by vcaputo** [comment]
@pmoust you'll be happy to know this has been merged upstream:
https://git.kernel.org/cgit/linux/kernel/git/mszeredi/vfs.git/commit/fs/overlayfs/copy_up.c?h=overlayfs-next&id=e4ad29fa0d224d05e08b2858e65f112fd8edd4fe

**Pull request merged**
