### PR TITLE
Linux 4.1.3

### PR DESCRIPTION
**Pull request by marineam**
4.0.9 remains for now since I didn't generate a config for arm64 (yet)

Since github doesn't show a diff of mostly coppied files well here are the changes to the rebased patch set:
```patch
diff -ru 4.0/03-x86-Lock-down-IO-port-access-when-module-security-is.patch 4.1/03-x86-Lock-down-IO-port-access-when-module-security-is.patch
--- 4.0/03-x86-Lock-down-IO-port-access-when-module-security-is.patch	2015-07-30 16:51:09.710537556 -0700
+++ 4.1/03-x86-Lock-down-IO-port-access-when-module-security-is.patch	2015-07-30 16:51:09.750535873 -0700
@@ -1,6 +1,8 @@
+From a86490e90244d673cf1705dbfeb705cca4d5322e Mon Sep 17 00:00:00 2001
 From: Matthew Garrett <matthew.garrett@nebula.com>
 Date: Thu, 8 Mar 2012 10:35:59 -0500
-Subject: [PATCH] x86: Lock down IO port access when module security is enabled
+Subject: [PATCH 03/14] x86: Lock down IO port access when module security is
+ enabled
 
 IO port access would permit users to gain access to PCI configuration
 registers, which in turn (on a lot of hardware) give access to MMIO register
@@ -14,7 +16,7 @@
  2 files changed, 7 insertions(+), 2 deletions(-)
 
 diff --git a/arch/x86/kernel/ioport.c b/arch/x86/kernel/ioport.c
-index 4ddaf66ea35f..00b440307419 100644
+index 37dae79..1ecc03c 100644
 --- a/arch/x86/kernel/ioport.c
 +++ b/arch/x86/kernel/ioport.c
 @@ -15,6 +15,7 @@
@@ -44,13 +46,13 @@
  	}
  	regs->flags = (regs->flags & ~X86_EFLAGS_IOPL) | (level << 12);
 diff --git a/drivers/char/mem.c b/drivers/char/mem.c
-index 297110c12635..efe38c1bc234 100644
+index 6b1721f..53fe675 100644
 --- a/drivers/char/mem.c
 +++ b/drivers/char/mem.c
 @@ -27,6 +27,7 @@
  #include <linux/export.h>
  #include <linux/io.h>
- #include <linux/aio.h>
+ #include <linux/uio.h>
 +#include <linux/module.h>
  
  #include <linux/uaccess.h>
@@ -65,3 +67,6 @@
  	if (!access_ok(VERIFY_READ, buf, count))
  		return -EFAULT;
  	while (count-- > 0 && i < 65536) {
+-- 
+2.3.6
+
diff -ru 4.0/13-efi-Add-EFI_SECURE_BOOT-bit.patch 4.1/13-efi-Add-EFI_SECURE_BOOT-bit.patch
--- 4.0/13-efi-Add-EFI_SECURE_BOOT-bit.patch	2015-07-30 16:51:09.710537556 -0700
+++ 4.1/13-efi-Add-EFI_SECURE_BOOT-bit.patch	2015-07-30 16:51:09.750535873 -0700
@@ -1,6 +1,7 @@
+From e029a605d5db033c5349142ef8a051658f586238 Mon Sep 17 00:00:00 2001
 From: Josh Boyer <jwboyer@fedoraproject.org>
 Date: Tue, 27 Aug 2013 13:33:03 -0400
-Subject: [PATCH] efi: Add EFI_SECURE_BOOT bit
+Subject: [PATCH 13/14] efi: Add EFI_SECURE_BOOT bit
 
 UEFI machines can be booted in Secure Boot mode.  Add a EFI_SECURE_BOOT bit
 for use with efi_enabled.
@@ -12,10 +13,10 @@
  2 files changed, 3 insertions(+)
 
 diff --git a/arch/x86/kernel/setup.c b/arch/x86/kernel/setup.c
-index a3d8174dedf9..26c5d54124c1 100644
+index 88dad73..d99c8c3 100644
 --- a/arch/x86/kernel/setup.c
 +++ b/arch/x86/kernel/setup.c
-@@ -1153,7 +1153,9 @@ void __init setup_arch(char **cmdline_p)
+@@ -1158,7 +1158,9 @@ void __init setup_arch(char **cmdline_p)
  
  #ifdef CONFIG_EFI_SECURE_BOOT_SIG_ENFORCE
  	if (boot_params.secure_boot) {
@@ -26,14 +27,17 @@
  #endif
  
 diff --git a/include/linux/efi.h b/include/linux/efi.h
-index cf7e431cbc73..c74cbd892032 100644
+index af5be03..aa4ee20 100644
 --- a/include/linux/efi.h
 +++ b/include/linux/efi.h
-@@ -942,6 +942,7 @@ extern int __init efi_setup_pcdp_console(char *);
- #define EFI_64BIT		5	/* Is the firmware 64-bit? */
+@@ -943,6 +943,7 @@ extern int __init efi_setup_pcdp_console(char *);
  #define EFI_PARAVIRT		6	/* Access is via a paravirt interface */
  #define EFI_ARCH_1		7	/* First arch-specific bit */
-+#define EFI_SECURE_BOOT		8	/* Are we in Secure Boot mode? */
+ #define EFI_DBG			8	/* Print additional debug info at runtime */
++#define EFI_SECURE_BOOT		9	/* Are we in Secure Boot mode? */
  
  #ifdef CONFIG_EFI
  /*
+-- 
+2.3.6
+
```

And here is the defconfig diff:
```patch
--- amd64_defconfig-4.0	2015-07-30 15:25:37.342674820 -0700
+++ amd64_defconfig-4.1	2015-07-30 16:51:09.750535873 -0700
@@ -61,7 +61,6 @@
 CONFIG_XEN_DEBUG_FS=y
 CONFIG_XEN_PVH=y
 CONFIG_PARAVIRT_TIME_ACCOUNTING=y
-CONFIG_MEMTEST=y
 CONFIG_GART_IOMMU=y
 CONFIG_NR_CPUS=128
 CONFIG_SCHED_SMT=y
@@ -88,6 +87,7 @@
 CONFIG_MTRR_SANITIZER_ENABLE_DEFAULT=1
 CONFIG_EFI=y
 CONFIG_EFI_STUB=y
+CONFIG_EFI_SECURE_BOOT_SIG_ENFORCE=y
 CONFIG_HZ_1000=y
 CONFIG_KEXEC=y
 CONFIG_KEXEC_FILE=y
@@ -458,6 +458,7 @@
 CONFIG_VMWARE_VMCI_VSOCKETS=m
 CONFIG_NETLINK_MMAP=y
 CONFIG_NETLINK_DIAG=m
+CONFIG_MPLS_ROUTING=m
 CONFIG_CGROUP_NET_PRIO=y
 CONFIG_BPF_JIT=y
 CONFIG_NET_DROP_MONITOR=m
@@ -582,6 +583,7 @@
 CONFIG_ATL1E=m
 CONFIG_ATL1C=m
 CONFIG_ALX=m
+# CONFIG_NET_CADENCE is not set
 CONFIG_B44=m
 CONFIG_CNIC=m
 CONFIG_TIGON3=m
@@ -807,6 +809,7 @@
 CONFIG_VIRT_DRIVERS=y
 CONFIG_VIRTIO_PCI=m
 CONFIG_VIRTIO_BALLOON=m
+CONFIG_VIRTIO_INPUT=m
 CONFIG_VIRTIO_MMIO=m
 CONFIG_HYPERV=m
 CONFIG_HYPERV_UTILS=m
@@ -908,6 +911,7 @@
 CONFIG_BLK_DEV_IO_TRACE=y
 CONFIG_UPROBE_EVENT=y
 CONFIG_FUNCTION_PROFILER=y
+CONFIG_MEMTEST=y
 CONFIG_STRICT_DEVMEM=y
 CONFIG_DEBUG_SET_MODULE_RONX=y
 CONFIG_DEBUG_BOOT_PARAMS=y
@@ -919,6 +923,7 @@
 CONFIG_SECURITY_NETWORK_XFRM=y
 CONFIG_SECURITY_SELINUX=y
 CONFIG_SECURITY_SELINUX_BOOTPARAM=y
+CONFIG_SECURITY_SELINUX_BOOTPARAM_VALUE=0
 CONFIG_SECURITY_SELINUX_DISABLE=y
 # CONFIG_CRYPTO_MANAGER_DISABLE_TESTS is not set
 CONFIG_CRYPTO_CRC32C_INTEL=m
@@ -938,4 +943,3 @@
 # CONFIG_XZ_DEC_ARM is not set
 # CONFIG_XZ_DEC_ARMTHUMB is not set
 # CONFIG_XZ_DEC_SPARC is not set
-CONFIG_EFI_SECURE_BOOT_SIG_ENFORCE=y
```

### CODE REVIEW

**Comment by mjg59** [comment]
LGTM

**Comment by marineam** [comment]
Hm, nm. something isn't happy:
```
arch/x86/built-in.o:(.rodata+0xb40): undefined reference to `stub_iopl'
arch/x86/built-in.o:(.rodata+0x1388): undefined reference to `sys32_vm86_warning'
arch/x86/built-in.o:(.rodata+0x1530): undefined reference to `sys32_vm86_warning'
```
checking where things got mixed up...

**Comment by marineam** [comment]
The kernel build worked after cleaning the cached working directory, so looks ok after all.

@mjg59 I noticed that 11-efi-Disable-secure-boot-if-shim-is-in-insecure-mode.patch is in the patch set but it is not listed and the ebuild and is broken as well. was excluding it intentional?

**Comment by marineam** [comment]
Added workaround for the build issue.

**Pull request merged**
