### PR TITLE
sys-libs/glibc: sync with gentoo stable, to 2.26

### PR DESCRIPTION
**Pull request by iaguis**
This bumps glibc to 2.26, which is the latest stable on gentoo.

I had to bump eclasses on portage-stable so this also bumps the EAPI of
dev-util/crosutils because EAPIs older than 4 are not allowed to use git-r3.

Part of coreos/portage-stable#674

### CODE REVIEW

**Comment by iaguis** [comment]
When trying to build this, I get an error building acbuild and actool:

```
/var/tmp/portage/app-emulation/acbuild-0.2.2-r1/temp/go-build635546586/b117/_x002.o: In function `my_makedev':
device_posix.cgo2.c:(.text+0xc4): undefined reference to `makedev'
...
```

<details><summary>Full error</summary>
<p>

```
# github.com/appc/acbuild/Godeps/_workspace/src/github.com/appc/spec/pkg/device
/var/tmp/portage/app-emulation/acbuild-0.2.2-r1/temp/go-build635546586/b117/_x002.o: In function `my_makedev':
device_posix.cgo2.c:(.text+0xc4): undefined reference to `makedev'
/var/tmp/portage/app-emulation/acbuild-0.2.2-r1/temp/go-build635546586/b117/_x002.o: In function `my_major':
device_posix.cgo2.c:(.text+0x3a): undefined reference to `major'
/var/tmp/portage/app-emulation/acbuild-0.2.2-r1/temp/go-build635546586/b117/_x002.o: In function `my_minor':
device_posix.cgo2.c:(.text+0x8a): undefined reference to `minor'
collect2: error: ld returned 1 exit status
# github.com/appc/acbuild/Godeps/_workspace/src/github.com/appc/spec/pkg/device
../gopath/src/github.com/appc/acbuild/Godeps/_workspace/src/github.com/appc/spec/pkg/device/device_posix.go: In function ‘my_major’:
../gopath/src/github.com/appc/acbuild/Godeps/_workspace/src/github.com/appc/spec/pkg/device/device_posix.go:27:10: warning: implicit declaration of function ‘major’; did you mean ‘my_major’? [-Wimplicit-function-declaration]
   return major(dev);
          ^~~~~
          my_major
../gopath/src/github.com/appc/acbuild/Godeps/_workspace/src/github.com/appc/spec/pkg/device/device_posix.go: In function ‘my_minor’:
../gopath/src/github.com/appc/acbuild/Godeps/_workspace/src/github.com/appc/spec/pkg/device/device_posix.go:33:10: warning: implicit declaration of function ‘minor’; did you mean ‘my_minor’? [-Wimplicit-function-declaration]
   return minor(dev);
          ^~~~~
          my_minor
../gopath/src/github.com/appc/acbuild/Godeps/_workspace/src/github.com/appc/spec/pkg/device/device_posix.go: In function ‘my_makedev’:
../gopath/src/github.com/appc/acbuild/Godeps/_workspace/src/github.com/appc/spec/pkg/device/device_posix.go:39:15: warning: implicit declaration of function ‘makedev’; did you mean ‘my_makedev’? [-Wimplicit-function-declaration]
        return makedev(maj, min);
               ^~~~~~~
               my_makedev
github.com/appc/acbuild/Godeps/_workspace/src/github.com/appc/spec/discovery
github.com/appc/acbuild/Godeps/_workspace/src/github.com/appc/spec/schema
github.com/appc/acbuild/Godeps/_workspace/src/github.com/appc/spec/pkg/acirenderer
```

</p>
</details>



Apparently it should `#include <sys/sysmacros.h>` and not `#include <sys/types.h>` (see [here](https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=6f03b7d078f9f8b855ec61c802e5b64edb11f599) or [here](https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=90d3156ebcade1197b21c37b5aaaaaf9fc9238eb)).

I don't have time to dig deeper into this until next week.

**Comment by iaguis** [comment]
> I get an error building acbuild and actool

This is weird because the file that's failing to build is `pkg/device/device_posix.go`, which shouldn't be built because [it has build tags `freebsd netbsd openbsd darwin`](https://github.com/appc/spec/blob/259c2eebc32df77c016974d5e8eed390d5a81500/pkg/device/device_posix.go#L15), [`device_linux.go`](https://github.com/appc/spec/blob/259c2eebc32df77c016974d5e8eed390d5a81500/pkg/device/device_linux.go) should be built instead.

Is it possible that the eclass that builds go programs doesn't set `GOOS` correctly? Maybe previous versions were building correctly because `device_posix.go` was building fine with older versions of glibc?

**Comment by iaguis** [comment]
Huh, if I check the versions we're building, they do have the right tags (or no tags, so it builds on linux):

https://github.com/appc/spec/blob/v0.5.1/pkg/tarheader/pop_posix.go
https://github.com/containers/build/blob/v0.2.2/Godeps/_workspace/src/github.com/appc/spec/pkg/device/device_posix.go

I think we should bump versions for these.

**Comment by iaguis** [comment]
I've built a developer image with this and things seem to work.

**Comment by iaguis** [comment]
Thanks for the review! Updated.

**Comment by dm0-** [comment]
@iaguis @dongsupark Thanks for submitting this; it will be in the alpha released on Tuesday.

**Pull request merged**
