### PR TITLE
Fix segfaults when reading long lines from /etc/gshadow

### PR DESCRIPTION
**Pull request by dm0-**
See coreos/bugs#1394.

### CODE REVIEW

**Comment by crawford** [comment]
So this won't allow us to read long lines, we'll just avoid the segfault, right?

**Comment by dm0-** [comment]
No, this patch passes up ERANGE which causes the buffer to be reallocated larger, then it retries parsing the line.  So, it should work as expected.

**Comment by philips** [comment]
@dm0- do you have a link to the upstream submission, just for tracking?

**Comment by dm0-** [comment]
I have sent the patch to the [libc-alpha list](https://sourceware.org/ml/libc-alpha/2016-06/msg01015.html).

**Comment by philips** [comment]
cc @mjg59 as our resident GNU expert in case @dm0- needs help getting upstream

**Comment by crawford** [comment]
LGTM

**Pull request merged**
