### PR TITLE
sys-apps/systemd: fix networkd-wait-online interface checks to prevents ...

### PR DESCRIPTION
**Pull request by mischief**
...hangs on systems with multiple NICs

### CODE REVIEW

**Comment by mischief** [comment]
this patch addresses coreos/bugs#279. i tested manually in qemu using the monitor to run `set_link <if> off`to simulate no-carrier. it would be nice if mantle supported sending monitor commands to each machine in the cluster so that this could be programatically tested in kola.

**Comment by marineam** [comment]
Could you provide the patch as a complete git commit generated by `git format-patch` please? That way it is trivial to import into a git branch. Ideally the patch here is the exact same email that gets sent to systemd-devel@

**Comment by mischief** [comment]
@marineam ptal

**Comment by crawford** [comment]
@mischief please rebase

**Comment by marineam** [comment]
LGTM

**Pull request merged**
