### PR TITLE
app-emulation/docker: use default cgroupdriver

### PR DESCRIPTION
**Pull request by crawford**
Fixes https://github.com/coreos/bugs/issues/1435.

/cc @aaronlevy @pbx0

### CODE REVIEW

**Comment by pbx0** [comment]
Are you leaving `$DOCKER_CGROUPS ` in the `ExecStart` line for compatibility reasons? I imagine most people override that line rather then the `Environment` if they were customizing this setting.  

Also, there are only two settings for this option anyway. So everyone is either moving from the systemd driver to cgroupfs or already on cgroupfs. Unless there exist configs that pin their daemon to the  systemd driver by overriding the environment.

**Comment by crawford** [comment]
Good point. @marineam do you think we should pull that option entirely? Anybody who overrode it to cgroupfs isn't going to be affected and I doubt anyone overrode the flag with the existing value (these cases would break).

**Comment by mischief** [comment]
:ship: :it: ?

**Comment by crawford** [comment]
@vcaputo and I talked it over and think it's good as is. We can deprecate the `DOCKER_CGROUPS` variable, but should probably leave it for now.

**Comment by vcaputo** [comment]
lgtm

**Pull request merged**
