### PR TITLE
flannel: load iptables kmod prior to start

### PR DESCRIPTION
**Pull request by eyakubovich**
flannel execs iptables which will try to load the
proper kernel mod if needed but that doesn't work
from container.

Fixes https://github.com/coreos/bugs/issues/270

### CODE REVIEW

**Comment by crawford** [comment]
LGTM

**Comment by philips** [comment]
lgtm

**Comment by marineam** [comment]
ip_tables alone is sufficient? You don't need any match extensions, targets, or nat support?

**Comment by eyakubovich** [comment]
@marineam ip_tables is sufficient (that's what iptables loads). The rest of the modules are pulled in as needed via request_module() mechanism. I was also stunned at first as to why only ip_tables.ko gets loaded but with Jed's help, we figured it out.

**Comment by marineam** [comment]
Ah, I had trouble with that in the past but was using nspawn which places completely different restrictions on containers.

**Pull request merged**
