### PR TITLE
app-emulation/rkt: v1.8.0

### PR DESCRIPTION
**Pull request by pbx0**

### CODE REVIEW

**Comment by mischief** [comment]
any testing done, like a rkt run etcd, coreos+rkt+k8s?

**Comment by pbx0** [comment]
Whats the bar on testing for this? I did not build it and use it within the sdk. It has been used and tested for rktnetes. I've used it a bit on CoreOS but by downloading the github release.

**Comment by mischief** [comment]
ideally rkt built with this ebuild is tested, since that's what we're actually going to ship.

**Comment by marineam** [comment]
Well, of kola gets a test for rktnetes then jenkins will take care of the rest ;-)

**Comment by marineam** [comment]
LGTM

**Comment by pbx0** [comment]
A kola test for rktnetes is certainly on my plate after we are all done with those related releases. I emerged rkt in the SDK and do some basic usage of it. Merging

**Pull request merged**
