### PR TITLE
sys-kernel/coreos-kernel: demote Xen framebuffer

### PR DESCRIPTION
**Pull request by jedsmith**
The Xen framebuffer driver on HVM EC2 instances fails to connect to `device/vfb/0` on the xenbus. This causes a 30-second boot delay on certain architectures (such as `m3`) since the support is compiled-in, and since Linux has the Xen framebuffer driver available, it attempts to initialize the framebuffer.

Demoting to a module increases boot speed by 30 seconds, because the boot-time code just infers that it has no driver for `device/vfb/0` and skips it. This also means that some crazy scenario in which the driver is actually needed is not impacted.

- Verified with CoreOS jed 653.0.0+2015-04-16-2113 on `m3.medium`.
- Fixes coreos/bugs#208.

#### Before

    [    1.880092] tsc: Refined TSC clocksource calibration: 2500.000 MHz
    [    6.119096] xenbus_probe_frontend: Waiting for devices to initialise: 25s...20s...15s...10s...5s...0s...
    [   31.024389] 
    [   31.026274] xenbus_probe_frontend: Timeout connecting to device: device/vfb/0 (local state 3, remote state 1)
    [   31.034053] xenbus_probe_frontend: Device with no driver: device/vbd/51712
    [   31.038947] xenbus_probe_frontend: Device with no driver: device/vbd/51728
    [   31.043718] xenbus_probe_frontend: Device with no driver: device/vif/0
    [   31.048430] rtc_cmos 00:02: setting system clock to 2015-02-24 00:42:02 UTC (1424738522)

#### After

    [    1.268163] registered taskstats version 1
    [    1.272211] xenbus_probe_frontend: Device with no driver: device/vfb/0
    [    1.278032] xenbus_probe_frontend: Device with no driver: device/vbd/51712
    [    1.283593] xenbus_probe_frontend: Device with no driver: device/vif/0
    [    1.288943] rtc_cmos 00:02: setting system clock to 2015-04-17 02:38:34 UTC (1429238314)

### CODE REVIEW

**Comment by crawford** [comment]
Sick. LGTM.

**Comment by marineam** [comment]
Merging so this doesn't linger. @mischief please include this change in your 4.0 bump

**Comment by pwaller** [comment]
Excellent! When will I find an AMI with this? :dancers:

**Comment by PierreKircher** [comment]
probably next week in the alpha

**Comment by jedsmith** [comment]
@pwaller If you're adventurous, you can use the image I built for testing here:

- https://storage.googleapis.com/users.developer.core-os.net/jed/boards/amd64-usr/653.0.0%2B2015-04-16-2113/coreos_production_ami_image.bin.bz2
- https://storage.googleapis.com/users.developer.core-os.net/jed/boards/amd64-usr/653.0.0%2B2015-04-16-2113/coreos_production_ami_image.bin.bz2.DIGESTS

It's unsigned, was made by me for a single purpose, and so forth. If you're going to use it, I wouldn't deploy it to production, but you can use it for evaluation. HTH

**Pull request merged**
