### PR TITLE
linux v4.4.4

### PR DESCRIPTION
**Pull request by mischief**
https://cdn.kernel.org/pub/linux/kernel/v4.x/ChangeLog-4.4.4

### CODE REVIEW

**Comment by crawford** [comment]
Sources?

**Comment by mischief** [comment]
i think i need more :coffee:

**Comment by mischief** [comment]
retest this please

**Comment by crawford** [comment]
Can you rebase this?

**Comment by mischief** [comment]
done

**Comment by crawford** [comment]
LGTM.

**Pull request merged**
