### PR TITLE
 app-emulation/docker: bump to v1.8.2

### PR DESCRIPTION
**Pull request by crawford**

### CODE REVIEW

**Comment by crawford** [comment]
Fixes https://github.com/coreos/bugs/issues/472.

**Comment by marineam** [comment]
Ebuild should be `1.8.2` not `docker-1.8.1-r2`

**Comment by crawford** [comment]
Updated.

**Comment by marineam** [comment]
LGTM

**Comment by vaijab** [comment]
How do you override this now? The only I can see going back to `json-file` logging is to replace entire `ExecStart` line.

The issue I have is that now kubernetes cannot read logs from docker.

**Comment by crawford** [comment]
It will be fixed. https://github.com/coreos/bugs/issues/483

**Pull request merged**
