### PR TITLE
app-emulation/rkt: check that ebuild and rkt CoreOS PXE versions match

### PR DESCRIPTION
**Pull request by mischief**

### CODE REVIEW

**Comment by steveeJ** [comment]
Add a link to https://github.com/coreos/rkt/blob/${PV}/stage1/usr_from_coreos/coreos-common.mk#L14 in the comment for convenience?

**Comment by marineam** [comment]
Maybe even add a test in src_prepare to assert that the version is correct.

**Comment by mischief** [comment]
@marineam ptal

**Comment by marineam** [comment]
LGTM

**Pull request merged**
