### PR TITLE
app-emulation/docker: revert to v1.5.0

### PR DESCRIPTION
**Pull request by crawford**

### CODE REVIEW

**Comment by mischief** [comment]
1.6.2 didnt make it in time? lgtm

**Comment by marineam** [comment]
Please don't revert  72d3d9b.

**Comment by marineam** [comment]
@mischief it may for alpha but we are going back to 1.5 for beta

**Comment by carmstrong** [comment]
> 1.6.2 didnt make it in time?

Are there more issues than what was fixed in 1.6.1?

**Comment by mischief** [comment]
@carmstrong it seems to have not landed yet https://github.com/docker/docker/pull/13133

**Comment by marineam** [comment]
@carmstrong some of the security changes in 1.6.1 were applicable to all versions, some were only applicable to 1.6.0. So 1.5 is a bit better off than 1.6.0 in that regard.

**Comment by crawford** [comment]
@marineam updated.

**Comment by marineam** [comment]
LGTM

**Pull request merged**
