### PR TITLE
Enable selinux

### PR DESCRIPTION
**Pull request by mjg59**
Include a missing package that caused some problems, and configure it so that systemd doesn't get unhappy when it attempts to use policy that doesn't exist in our configuration.

### CODE REVIEW

**Comment by marineam** [comment]
To make it clearer which semanage ebuild is in use (and contains CoreOS modifications) please drop the unneeded ebuild versions. Otherwise we are more likely to make mistakes next time we deal with this package.

**Comment by mjg59** [comment]
Done.

**Comment by marineam** [comment]
if we are going to keep the live 9999 ebuild could you make the same changes to it so it remains in sync?

**Comment by marineam** [comment]
9999 is still missing the `echo "handle-unknown=allow" >> "${S}/src/semanage.conf"` change.

**Comment by marineam** [comment]
LGTM

**Comment by marineam** [comment]
Since the audit stuff landed could you rebase this please? :)

**Comment by mjg59** [comment]
Testing the rebase right now

**Comment by marineam** [comment]
Ship it! :)

**Pull request merged**
