### PR TITLE
sys-kernel/coreos-{kernel,sources}: fix build

### PR DESCRIPTION
**Pull request by crawford**
This should have been in https://github.com/coreos/coreos-overlay/pull/1867.

### CODE REVIEW

**Comment by mischief** [comment]
lgtm

**Comment by crawford** [comment]
```
../source/drivers/acpi/acpica/evxfregn.c
../source/fs/overlayfs/copy_up.c: In function 'ovl_copy_xattr':
../source/fs/overlayfs/copy_up.c:89:4: error: label 'out_free_value' used but not defined
    goto out_free_value;
    ^
```

**Comment by mischief** [comment]
sure glad i set up that PR builder :trollface:

**Comment by crawford** [comment]
Yeah, I screwed up that last one pretty good. This should work a bit better.

**Comment by mischief** [comment]
retest this please

**Comment by mischief** [comment]
retest this please

**Comment by mischief** [comment]
retest this please

**Comment by mischief** [comment]
retest this please

**Comment by crawford** [comment]
There we go.

**Comment by mischief** [comment]
lgtm

**Pull request merged**
