### PR TITLE
sys-kernel/coreos-kernel: bump to 4.3.3

### PR DESCRIPTION
**Pull request by crawford**

### CODE REVIEW

**Comment by mischief** [comment]
you will need to remove 0021-net-switchdev-fix-return-code-of-fdb_dump-stub.patch from coreos-sources as it has been applied as of 4.3.3.

**Comment by crawford** [comment]
Dang, I didn't push the latest commit.

**Comment by crawford** [comment]
Wait......... yes I did. GitHub's caching is always screwed up.

**Comment by vcaputo** [comment]
lgtm, but I'd like it if we kept a branch @ github.com/coreos/linux in sync with the patchset applied in the ebuild, so the set could be reproduced exactly via `git format-patch` of the branch.

**Comment by crawford** [comment]
I can create a v4.3.3-coreos branch, though I would rather not manually keep them in sync.

**Comment by crawford** [comment]
@vcaputo https://github.com/coreos/linux/pull/4

**Comment by vcaputo** [comment]
lgtm

**Pull request merged**
