### PR TITLE
Revert "app-emulation/docker: bump to v1.6.0"

### PR DESCRIPTION
**Pull request by marineam**
Reverts coreos/coreos-overlay#1211

That PR didn't properly update the patches included in the ebuild.

### CODE REVIEW

**Comment by mischief** [comment]
lgtm

**Comment by carmstrong** [comment]
@marineam What did I do wrong?

**Comment by mischief** [comment]
@carmstrong the build failed because a patch in the ebuild was submitted upstream and no longer applied.

**Comment by carmstrong** [comment]
> the build failed because a patch in the ebuild was submitted upstream and no longer applied.

Gotcha.

**Pull request merged**
