### PR TITLE
coreos-base/update-ssh-keys: req newer coreos-init

### PR DESCRIPTION
**Pull request by sdemos**
coreos-init versions older than 0.0.1-r152 still have the
update-ssh-keys shell script which means we the update-ssh-keys package
fails to install. to fix this, we make coreos-base/update-ssh-keys
depend on a new enough version of coreos-init.

### CODE REVIEW

**Comment by sdemos** [comment]
reworded the commit message and rebased onto `master`.

**Comment by euank** [comment]
I think this should also bump the revision of the symlink.

**Comment by sdemos** [comment]
bumped the revision version.

**Pull request merged**
