### PR TITLE
coreos-{kernel,sources}: bump to 4.5

### PR DESCRIPTION
**Pull request by crawford**

### CODE REVIEW

**Comment by crawford** [comment]
Should resolve https://github.com/coreos/bugs/issues/1156.

**Comment by mischief** [comment]
it looks like a patch file is missing or the ebuild needs to be updated.

**Comment by crawford** [comment]
It looks like the ebuild needs to be named 4.5.0 instead of 4.5.

**Comment by mischief** [comment]
the naming only matters for coreos-sources but not coreos-kernel..? weird.

lgtm

**Comment by crawford** [comment]
I updated the kernel ebuild to be 4.5.0 as well.

**Pull request merged**
