### PR TITLE
net-misc/google-cloud-sdk: add gcloud and gsutil

### PR DESCRIPTION
**Pull request by crawford**

### CODE REVIEW

**Comment by marineam** [comment]
This isn't going to work, the shipped python doesn't have ssl support.

**Comment by crawford** [comment]
Hmmm, I did basic tests and it seemed to work well. Maybe it wasn't using SSL?

**Comment by marineam** [comment]
What was the basic tests? all APIs are over SSL. We haven't needed it before because the daemon and scripts just talk to the local metadata service which isn't SSL.

**Comment by crawford** [comment]
I authenticated and listed the vm images in the test project.

**Comment by marineam** [comment]
Ok. I'm scared, did we goof something at some point and start linking openssl?

**Comment by marineam** [comment]
On a current alpha machine this explodes as expected:

```
marineam@marineam-6 ~/google-cloud-sdk $ export CLOUDSDK_PYTHON=/usr/share/oem/p
ython/bin/python
marineam@marineam-6 ~/google-cloud-sdk $ ./bin/gcloud 
Traceback (most recent call last):
  File "/home/marineam/google-cloud-sdk/./lib/gcloud.py", line 53, in <module>
    main()
  File "/home/marineam/google-cloud-sdk/./lib/gcloud.py", line 31, in main
    import googlecloudsdk.gcloud_main
  File "/home/marineam/google-cloud-sdk/lib/googlecloudsdk/gcloud_main.py", line 28, in <module>
    from googlecloudsdk.calliope import backend
  File "/home/marineam/google-cloud-sdk/lib/googlecloudsdk/calliope/backend.py", line 26, in <module>
    from googlecloudsdk.calliope import actions
  File "/home/marineam/google-cloud-sdk/lib/googlecloudsdk/calliope/actions.py", line 23, in <module>
    from googlecloudsdk.calliope import markdown
  File "/home/marineam/google-cloud-sdk/lib/googlecloudsdk/calliope/markdown.py", line 22, in <module>
    from googlecloudsdk.calliope import base
  File "/home/marineam/google-cloud-sdk/lib/googlecloudsdk/calliope/base.py", line 21, in <module>
    from googlecloudsdk.calliope import arg_parsers
  File "/home/marineam/google-cloud-sdk/lib/googlecloudsdk/calliope/arg_parsers.py", line 54, in <module>
    from googlecloudsdk.core import log
  File "/home/marineam/google-cloud-sdk/lib/googlecloudsdk/core/log.py", line 24, in <module>
    from googlecloudsdk.core import properties
  File "/home/marineam/google-cloud-sdk/lib/googlecloudsdk/core/properties.py", line 1150, in <module>
    VALUES = _Sections()
  File "/home/marineam/google-cloud-sdk/lib/googlecloudsdk/core/properties.py", line 207, in __init__
    self.proxy = _SectionProxy()
  File "/home/marineam/google-cloud-sdk/lib/googlecloudsdk/core/properties.py", line 842, in __init__
    valid_proxy_types = sorted(config.GetProxyTypeMap().keys())
  File "/home/marineam/google-cloud-sdk/lib/googlecloudsdk/core/config.py", line 681, in GetProxyTypeMap
    from httplib2 import socks
  File "/home/marineam/google-cloud-sdk/./lib/third_party/httplib2/__init__.py", line 930, in <module>
    class HTTPSConnectionWithTimeout(httplib.HTTPSConnection):
AttributeError: 'module' object has no attribute 'HTTPSConnection'
```

I'm guessing you were using a dev image which of course does include a full python.

**Comment by crawford** [comment]
I built the image with `emerge-amd64-usr ignition coreos-kernel && ./build_image prod --replace && ./image_to_vm.sh --prod --format=gce && ore upload` so I'm not sure how the extra python got in there (haven't investigated yet).

**Pull request closed without merging**
