### PR TITLE
app-emulation/docker: revert and backport stats api fix

### PR DESCRIPTION
**Pull request by crawford**
Revert back to 1.11.2 and include a fix for the stats API.

### CODE REVIEW

**Comment by crawford** [comment]
Fixes https://github.com/coreos/bugs/issues/1526.

**Comment by mischief** [comment]
@crawford it appears your revert will goto 1.11.2, not 1.10.3. is that intended?

**Comment by crawford** [comment]
@mischief yes. 1.10.3 shipped in the Stable. We're going to stick with 1.11.2 for Beta.

**Comment by mischief** [comment]
ok, your original message said 1.10.3 so i wanted to check. lgtm

**Comment by crawford** [comment]
woops, good catch.

**Pull request merged**
