### PR TITLE
coreos-init: cease enabling socket-activated sshd

### PR DESCRIPTION
**Pull request by vcaputo**
Maybe fixes https://github.com/coreos/bugs/issues/909
Fixes https://github.com/coreos/bugs/issues/966

### CODE REVIEW

**Comment by marineam** [comment]
This is certainly a thing we should do but I'm unsure how to safely migrate. Users who have changed the port or similar by modifying sshd.socket are going to loose that change. If the user has sshd.socket enabled in /etc I'm not sure whether it or sshd.service is more likely to win the conflict resolution. The migration question is the biggest reason we've stuck with this setup so far despite it confusing so many of our users, other distros don't run sshd in this manner so it is rather unexpected.

**Comment by vcaputo** [comment]
Capturing OOB discussion:

Due to the potential for customized sshd_configs and explicit sshd.socket enables / customizations, blindly switching to this simply enabled sshd.service carries some risk for upgrades.

Instead we'll implement a generator which determines if sshd.service can safely be enabled, otherwise enabling sshd.socket.

**Comment by vcaputo** [comment]
@marineam so this is now simply removing the sshd.socket enable, deferring sshd enablement to  https://github.com/coreos/init/pull/188

**Comment by vcaputo** [comment]
I *hope* coreos or whatever it's called now under redhat no longer socket-activates sshd.

**Comment by bgilbert** [comment]
Container Linux still socket-activates sshd, and we have no plans to change that: https://github.com/coreos/bugs/issues/966#issuecomment-423697629.  Fedora CoreOS will (hopefully) avoid doing so.

**Pull request closed without merging**
