### PR TITLE
Update docker to include SELinux fixes

### PR DESCRIPTION
**Pull request by mjg59**

### CODE REVIEW

**Comment by marineam** [comment]
Missing a change to the git hash in the ebuild

**Comment by mjg59** [comment]
Ugh yes miscommit

**Comment by crawford** [comment]
LGTM

**Comment by marineam** [comment]
Commented on https://github.com/coreos/docker/pull/11 about the difference between this and the earlier revision of the commit.

**Comment by mjg59** [comment]
Should refer to the correct version now

**Comment by marineam** [comment]
LGTM

**Pull request merged**
