### PR TITLE
arm64_defconfig: Set CONFIG_MODULE_SIG

### PR DESCRIPTION
**Pull request by glevand**
Needed.  Also fixes kernel build errors.

### CODE REVIEW

**Comment by mischief** [comment]
are you editing this by hand or did you use scripts/kernel_menuconfig? aren't there other MODULE_SIG_* parameters needed like in amd64's config?

**Comment by glevand** [comment]
@mischief Yes, generated with savedefconfig.
I pushed out an update that adds CONFIG_MODULE_SIG_SHA256, which is what amd64 has.

**Comment by mischief** [comment]
@glevand bump ebuild revision and LGTM

**Comment by glevand** [comment]
Bumped ebuild to coreos-kernel-4.4.0-r1.

**Pull request merged**
