### PR TITLE
app-emulation/docker: remove deprecated --daemon flag

### PR DESCRIPTION
**Pull request by mischief**

### CODE REVIEW

**Comment by marineam** [comment]
For my own reference, when did this change?

**Comment by marineam** [comment]
ebuild needs a rev bump

**Comment by mischief** [comment]
@marineam https://github.com/docker/docker/blob/master/CHANGELOG.md#180-2015-08-11

"Replace docker -d with new subcommand docker daemon"

**Comment by marineam** [comment]
Ok. please bump the revision of the ebuild then LGTM

**Comment by mischief** [comment]
@marineam ptal...

**Comment by marineam** [comment]
[LGTM](http://lgtm.in/i/e7EVBsGmq)

**Pull request merged**
