### PR TITLE
 dev-libs/openssl: Update to 1.0.2t for GLSA 201911-04

### PR DESCRIPTION
**Pull request by bgilbert**

### CODE REVIEW

**Comment by bgilbert** [comment]
https://jenkins-container-linux.apps.ci.centos.org/job/os/job/manifest/404/cldsv/

**Comment by ajeddeloh** [comment]
Manifest job is failing for unrelated reasons.

**Comment by bgilbert** [comment]
It was failing because my `LOCAL_MANIFEST` was incorrect.

**Comment by bgilbert** [comment]
Tests look OK.

**Pull request merged**
