### PR TITLE
app-emulation/docker: bump to v1.6.0

### PR DESCRIPTION
**Pull request by carmstrong**
https://github.com/docker/docker/commit/47496519da9664202d900d3635bb840509fa9647

### CODE REVIEW

**Comment by mischief** [comment]
funny, i just made this change but didn't submit a pr :)

**Comment by mischief** [comment]
i think we will hold off on this for now. i found some bugs relating to 1.6 and there may be more

docker/docker#12489
docker/docker#12515
docker/docker#12564

**Comment by marineam** [comment]
Merging this so we can play with 1.6 over the coming week, possibly pulling in patches from upstream if any of those bugs get fixed. If all goes well it'll be in next week's alpha.

**Pull request merged**
