### PR TITLE
profiles/coreos/base: use openssl 1.0.2e for security fixes

### PR DESCRIPTION
**Pull request by pbx0**
https://github.com/coreos/bugs/issues/1017

### CODE REVIEW

**Comment by mischief** [comment]
needs https://github.com/coreos/portage-stable/pull/369 commits cherry-picked into a new branch in portage-stable to actually take effect.

**Comment by pbx0** [comment]
@mischief ok starting with the portage-stable commit I got from https://github.com/coreos/manifest/blob/build-835/build-835.xml I cherry-picked those two changes into it and created a build-835 branch here: https://github.com/coreos/portage-stable/commits/build-835

Presumably, I just need to bump the manifest commit for portage-stable in build-835 and then this commit will take effect?

**Comment by mischief** [comment]
lgtm

**Comment by marineam** [comment]
LGTM

**Pull request merged**
