### PR TITLE
Fix flannel-wrapper etc-ssl-certs volume path

### PR DESCRIPTION
**Pull request by zunkree**

### CODE REVIEW

**Comment by zunkree** [comment]
PR ready for review

**Comment by lucab** [comment]
This is probably going to conflict with https://github.com/coreos/coreos-overlay/pull/2570, can you please introduce the same `coreos-` prefix here?. Other than that, pinging @crawford to know whether there is some hidden story behind this or if it is just a plain typo.

**Comment by crawford** [comment]
Looks like it was a typo.

**Comment by zunkree** [comment]
Conflicts resolved, branch has been rebased to master.

**Pull request merged**
