### PR TITLE
sys-kernel/coreos-modules: Add new kernel modules

### PR DESCRIPTION
**Pull request by TerraTech**
* Reworked pull request into single release bump as requested: https://github.com/coreos/coreos-overlay/pull/2093

  * Add 3ware 7xxx/8xxx series hardware raid
  ** https://github.com/coreos/bugs/issues/1268

  * Add National Semiconductor DP8381x series PCI Ethernet
  ** https://github.com/coreos/bugs/issues/1280

  * Add via-rhine network support

### CODE REVIEW

**Comment by mischief** [comment]
@TerraTech please update your commit message to have `sys-kernel/coreos-modules` prefix.

did you use the SDK's `kernel_menuconfig` script to make these changes, or at least use savedefconfig?

**Comment by TerraTech** [comment]
@mischief I've updated to use the correct prefix.

Yes, I used `savedefconfig` as the base, made the kernel config changes, and ran scripts/diffconfig afterwards then hand patched the config file in the overlay tree.  At the time, I did not know about the SDK's `kernel_menuconfig` so I did manually.

Sorry about all the hassle trying to get the pull requests accepted.  This is my first go at it and I'm still learning what is acceptable and what isn't.

**Comment by mischief** [comment]
@TerraTech can you rebase this? we've just merged the 4.7 kernel.

**Comment by TerraTech** [comment]
@mischief rebased and pushed for 4.7 kernel

**Comment by mischief** [comment]
hi, @TerraTech, you also need to bump the revision of `sys-kernel/coreos-kernel` ebuild for this to take effect, so: `git mv coreos-kernel-4.7.0{,-r1}.ebuild`.

**Comment by TerraTech** [comment]
@mischief I thought they were independent, thanks for the heads up!

**Comment by mischief** [comment]
lgtm, thanks!

**Comment by TerraTech** [comment]
@mischief @crawford Thank you for your assistance in getting this accepted and merged.

**Comment by crawford** [comment]
Thanks for your patience. Portage can be a beast.

**Pull request merged**
