### PR TITLE
sys-apps/baselayout: disable coreos-profile.sh on cros_host

### PR DESCRIPTION
**Pull request by vcaputo**

### CODE REVIEW

**Comment by mischief** [comment]
lgtm

**Comment by vcaputo** [comment]
@marineam ptal, is this a reasonable approach?

**Comment by marineam** [comment]
LGTM, although I'd leave off `-f` to force a failure if the file ever moves or renamed but the ebuild doesn't get updated.

**Comment by vcaputo** [comment]
oki doke, thanks marineam

**Comment by mischief** [comment]
excellent!

```
$ bash -l
Failed to get D-Bus connection: Operation not permitted
Update Strategy: No Reboots
Failed to get D-Bus connection: Operation not permitted
mischief@delta /mnt/host/source/src/scripts $ 
```

->

```
mischief@delta /mnt/host/source/src/scripts $ bash -l
mischief@delta /mnt/host/source/src/scripts $ 
```

**Pull request merged**
