### PR TITLE
Open iscsi

### PR DESCRIPTION
**Pull request by ppickfor**
my first pull request so any advise welcome :)

open iscsi userspace tools

sample cloud config

```
#cloud-config
coreos:
  units:
    - name: systemd-sysctl.service
      command: restart
    - name: iscsid.socket
      command: start
    - name: open-iscsi-discoverydb@.service
      content: |
        [Unit]
        Description=Open-iSCSI discoverydb for sendtargets portal %I
        Documentation=man:iscsiadm(8)
        After=network-online.target iscsid.service 
        [Service]
        Type=oneshot
        ExecStart=/usr/sbin/iscsiadm -m discoverydb -t st -p %I -D
        RemainAfterExit=true
    - name: open-iscsi-discoverydb@station30.netremedies.ca.service
      command: start
    - name: open-iscsi-target@.path
      content: |
        [Unit]
        Description=Watch for Open-iSCSI target %i
        Documentation=man:iscsiadm(8)
        [Path]
        PathExistsGlob=/etc/iscsi/send_targets/*/*%i*
    - name: open-iscsi-target@.service
      content: |
        [Unit]
        Description=Open-iSCSI target %i
        Documentation=man:iscsiadm(8)
        After=remote-fs.target iscsid.service 
        [Service]
        Type=oneshot
        ExecStart=/usr/sbin/iscsiadm -m node -T %i -l
        ExecStop=/usr/sbin/iscsiadm -m node -T %i -u
        RemainAfterExit=true
    - name: open-iscsi-target@iqn.2012-10.ca.netremedies:athlon64.netremedies.ca.data.docker.path
      command: start
    - name: var-lib-docker.mount
      command: start
      content: |
        [Unit]
        Description=Mount to /var/lib/docker
        Before=docker.service
        After=network-online.target open-iscsi-target@iqn.2012-10.ca.netremedies:athlon64.netremedies.ca.data.docker.service
        Wants=open-iscsi-target@iqn.2012-10.ca.netremedies:athlon64.netremedies.ca.data.docker.service
        [Mount]
        What=/dev/disk/by-uuid/ae0ea887-9867-449c-87c4-7438e07a3e31
        Where=/var/lib/docker
        Type=btrfs
        Options=rw,noatime,space_cache,subvol=@docker,noauto,x-systemd.automount,x-systemd.device-timeout=30
    - name: docker.service
      command: start
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
write_files:
  - path: /etc/iscsi/initiatorname.iscsi
    content: |
      InitiatorName=iqn.2012-10.ca.netremedies:athlon64.netremedies.ca
  - path: /etc/sysctl.d/sysrq.conf
    content: |
      kernel.sysrq=1
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCzWmeDdcIu4fvVkaJvGUb/M1g2KWgfSNM9A9p+xnXVcLtL2fulvXHJF5maeJKagmN9HBVacNkK4QyhiOulCzeU9Q0Osw050Djw5s5r+XPotU24WDCnjbxY2WqSF8C3RC5Ijejgm7ib4nINdhTvZRjdO9IyJYuSr0Tl7ZAux89oEdNp/IG8DmsNIevdvdnJUYFTiMv8CiqZcN6zArAsYPpqzT+SmzzdyShCXJtWCqMMYDzLC7FhFqkkBErlnEYtdFIHfE2/0PN1V0RJCNDsQ7+2GxYGJ4LaahFFopiwxOQjxNxNrIWDUXxw1dPA2mx8x0Lhmwf5oxwr8e5fr181Ud75 peter@ubuntu64
```

### CODE REVIEW

**Comment by azimut** [comment]
+1

**Comment by ScOut3R** [comment]
+1

**Comment by proteansec** [comment]
+1

**Comment by glevand** [comment]
It seems you changed the keywords from ~amd64 to amd64 in 2.0.873-r1.  I think it better to either use the stable version (2.0.872-r2), or add open-iscsi with ~amd64 to the package.accept_kewords file if there are problems with 2.0.872-r2

**Comment by dlaube** [comment]
+1

**Comment by mian3010** [comment]
+1

**Comment by marineam** [comment]
Finally landed in a release: https://github.com/coreos/bugs/issues/634 https://github.com/coreos/manifest/releases/tag/v1029.0.0

**Pull request closed without merging**
