### PR TITLE
sys-libs/timezone-data: sync with upstream stable ebuild

### LINKED ISSUE #1265: Timezone doesn't get correct default value
After upgrading to 681.0.0 (see #1252), we started seeing this in our logs:
```
May 27 18:36:33 fleet-01 kube-controller-manager[3463]: I0527 18:36:33.215241    3463 nodecontroller.go:610] Evicting pods2: 2015-05-27 18:36:33.215232055 +0000 Local time zone must be set--see zic manual page is later than 2015-05-27 18:36:33.215230741 +0000 Local time zone must be set--see zic manual page + 4m20s
```
We also saw:
```
core@fleet-01 ~ $ ls -l /etc/localtime
-rw-r--r-- 1 root root 264 May 14 00:47 /etc/localtime
core@fleet-01 ~ $ cat /etc/localtime
TZif21Local time zone must be set--see zic manual pageTZif21�Local time zone must be set--see zic manual page
<Local time zone must be set--see zic manual page>0
```
Explicitly setting the timezone to UTC resolved the issue:
```
core@fleet-01 ~ $ sudo timedatectl set-timezone UTC
core@fleet-01 ~ $ ls -l /etc/localtime
lrwxrwxrwx 1 root root 25 May 27 18:34 /etc/localtime -> ../usr/share/zoneinfo/UTC
core@fleet-01 ~ $ cat /etc/localtime
TZif2UTCTZif2�UTC
UTC0
```
The documentation states that UTC is the default timezone, but that appears to be only partially correct: https://coreos.com/docs/cluster-management/setup/configuring-date-and-timezone/

### PR DESCRIPTION
**Pull request by mischief**
code from the ebuild has been removed so that /etc/localtime is not
created.

fixes #1265

### CODE REVIEW

**Comment by crawford** [comment]
Can you break this into two commits?

**Comment by mischief** [comment]
@crawford ptal

**Comment by crawford** [comment]
LGTM

**Comment by glevand** [comment]
@mischief Should your second patch rename timezone-data-2015b.ebuild to timezone-data-2015b-r1.ebuild?

**Comment by marineam** [comment]
Oh, yes, please revbump

**Comment by mischief** [comment]
done.

**Comment by crawford** [comment]
@glevand good catch.

**Comment by marineam** [comment]
LGTM

**Pull request merged**
