### PR TITLE
app-emulation/rkt: bump to v0.5.5 and add gc timer

### PR DESCRIPTION
**Pull request by crawford**
WIP

### CODE REVIEW

**Comment by crawford** [comment]
Sticking with 0.5.5 for now.

**Comment by jonboulle** [comment]
Looks OK

**Comment by marineam** [comment]
Please update to a less aggressive schedule, I don't think we need to be running this every 10 minutes.

**Comment by crawford** [comment]
@marineam I went with a 1d grace period and 12h periodic timer.

**Comment by marineam** [comment]
[LGTM](http://lgtm.in/i/Akncv6Vfq)

**Pull request merged**
