### PR TITLE
app-admin/locksmith: issue 960

### PR DESCRIPTION
**Pull request by pbx0**
This effectively backports the solution to issue https://github.com/coreos/bugs/issues/944 into the 766 build of coreos-overlay. See https://github.com/coreos/bugs/issues/960

### CODE REVIEW

**Comment by vcaputo** [comment]
bump the ebuild

**Comment by pbx0** [comment]
Bumped ebuild to 0.3.0.1 to not confuse with the git tag 0.3.1. PTAL

**Comment by vcaputo** [comment]
the established convention is to just use an -rN suffix, so in this case locksmith-0.3.0-r1.ebuild

**Comment by pbx0** [comment]
@vc 0.3.0-r1 now

**Comment by vcaputo** [comment]
lgtm

**Comment by marineam** [comment]
LGTM

**Pull request merged**
