### PR TITLE
sys-apps/systemd: bump to v220-coreos

### PR DESCRIPTION
**Pull request by crawford**
WIP. The commit hash will need to be updated once @mischief lands his domain-name fix.

### CODE REVIEW

**Comment by marineam** [comment]
Please also update the header to reflect the upstream revision of systemd-9999.ebuild you are syncing with.

**Comment by marineam** [comment]
looks good, so far

**Comment by crawford** [comment]
Updated the commit hash.

**Comment by jonboulle** [comment]
lgtm

**Pull request merged**
