### PR TITLE
repo: update repo wrapper script to 1.22

### PR DESCRIPTION
**Pull request by marineam**

### CODE REVIEW

**Comment by mischief** [comment]
any particular reason to update?

**Comment by marineam** [comment]
Because repo will constantly complain otherwise:

```
... A new repo command ( 1.22) is available.
... You should upgrade soon:

    cp /mnt/host/source/.repo/repo/repo /usr/lib/python-exec/python2.7/repo
```

**Comment by marineam** [comment]
Of course you shouldn't actually execute the suggested command as that copy of repo is installed by this ebuild, not the user.

**Comment by crawford** [comment]
LGTM

**Pull request merged**
