### PR TITLE
overlay: add rocket

### PR DESCRIPTION
**Pull request by polvi**
this is just an alpha for testing. Need rocket to mature more before having proper ebuild.

### CODE REVIEW

**Comment by marineam** [comment]
Before this lands in the image downloading things in the unpack stage will need to be removed but this is fine for a first pass for testing. Perhaps add a TODO?

[LGTM](http://www.lgtm.in/i/YSawp1W9q)

**Comment by polvi** [comment]
I think this is the real solution: coreos/rocket#429

**Comment by marineam** [comment]
https://github.com/coreos/rocket/issues/429 isn't everything, the `go get` of appc will also need to be removed.

**Comment by jonboulle** [comment]
Yes, I already have a pr up against Rocket to vendor the spec.

**Pull request merged**
