### PR TITLE
Fixed VMware condition for VMware images which run on Virtualbox

### PR DESCRIPTION
**Pull request by kayrus**
/cc @crawford 

Fixed an issue which occurred with one of our customer.

### CODE REVIEW

**Comment by crawford** [comment]
Why is he running a VMware image on VirtualBox?

**Comment by kayrus** [comment]
@crawford because he can ;)

**Comment by crawford** [comment]
I assume coreos-cloudinit fails to run with something like "no providers were available in time". If that is the case, I would argue that it is working correctly.

**Comment by kayrus** [comment]
@crawford this fix doesn't harm at all. you can see that `vmtoolsd.service` has this condition too. Do you have any objective reasons to close this PR?

**Comment by crawford** [comment]
vmtoolsd.service shouldn't have this condition either and it should be removed. The VMware images should only be able to run inside of VMware and this change gives the false sense that we are going to support running these images in non-VMware environments.

**Pull request closed without merging**
