### PR TITLE
util-linux: don't bother excluding misc small utilities

### PR DESCRIPTION
**Pull request by marineam**
We may not *need* things like fsck.minix but it does get the systemd
test suite to pass. setarch should be there. fdformat and others are no
longer built by the ebuild.

### CODE REVIEW

**Comment by crawford** [comment]
Are these tools also going to wind up in the image?

**Comment by marineam** [comment]
Yes, we can any to the prod specific install mask if they are worth continuing to exclude.

**Comment by crawford** [comment]
Does it make sense to continue to exclude these utilities in the image (but leave them in the SDK)?

**Comment by marineam** [comment]
Perhaps, I don't really care one way or the other.

**Comment by crawford** [comment]
Meh, LGTM.

**Pull request merged**
