### PR TITLE
net-libs/libtirpc: import from portage-stable

### PR DESCRIPTION
**Pull request by mischief**

### CODE REVIEW

**Comment by crawford** [comment]
LGTM

**Comment by marineam** [comment]
Could you prune this down to just the ebuild we are currently using any files it needs? No need to for the rest and it makes it harder to identify what our local changes are. So ChangeLog, metadata, can all go. Manifest will stay but should be pruned. `ebuild foo.ebuild digest` will regenerate it.

**Comment by mischief** [comment]
PTAL

**Comment by marineam** [comment]
LGTM

**Pull request merged**
