### PR TITLE
sys-apps/rng-tools: Add rng-tools

### PR DESCRIPTION
**Pull request by crawford**
Pulled the systemd unit into rng-tools-4-r5.ebuild and dropped the confd and initd files.

### CODE REVIEW

**Comment by mischief** [comment]
any reason not to refresh and merge this?

**Comment by crawford** [comment]
Depends on https://github.com/coreos/portage-stable/pull/204.

**Comment by crawford** [comment]
This will _include_ rng-tools in the image, but it will not enable it by default. We will need a systemd-generator that detects if a TMP is present, /dev/hwrng is present, or the CPU supports RDRAND and enables the service.

**Comment by marineam** [comment]
[LGTM](http://lgtm.in/i/etjbIlrCn)

**Pull request merged**
