### PR TITLE
eclass: add get_semver() to cros-workon eclass

### PR DESCRIPTION
**Pull request by mischief**

### CODE REVIEW

**Comment by marineam** [comment]
How about just put this in cros-workon and export a read-only variable like CROS_WORKON_VERSION

**Comment by marineam** [comment]
Hm, actually, leave as a function since not all things using crosworkon will have tags. but that seems like the proper place for the function to live.

**Comment by mischief** [comment]
ptal

**Comment by marineam** [comment]
Just need to update the commit description and then LGTM

**Pull request merged**
