### PR TITLE
app-admin/kubelet: add service unit

### PR DESCRIPTION
**Pull request by crawford**

### CODE REVIEW

**Comment by kelseyhightower** [comment]
LGTM

**Comment by UserTaken** [comment]
This could have the same problem as https://github.com/coreos/coreos-overlay/pull/1379.

**Comment by crawford** [comment]
@UserTaken -_- yep. You're right.

**Comment by crawford** [comment]
@UserTaken fixed over here https://github.com/coreos/coreos-overlay/pull/1429.

**Pull request merged**
