### PR TITLE
arm64 dependancies

### PR DESCRIPTION
**Pull request by andrejro**

### CODE REVIEW

**Comment by marineam** [comment]
I think the main thing that needs to change here is for cloudinit and docker the version to use should be determined by KEYWORDS in the ebuilds rather than special dependencies in the coreos meta ebuild.

**Comment by marineam** [comment]
otherwise looks good

**Comment by marineam** [comment]
I mucked around with the docker ebuild a bit further, results are here: https://github.com/coreos/coreos-overlay/pull/1554

**Comment by andrejro** [comment]
Fixed the ebuild special dependencies.

**Comment by marineam** [comment]
I've merged this via my own branch which rebased your changes on a different docker ebuild in order to keep the 1.7.1 version master in sync with the one we have been iterating on in the 766 release branch.

Now to give this all a test spin! Thanks :)

**Pull request closed without merging**
