### PR TITLE
Mayday

### PR DESCRIPTION
**Pull request by mischief**

### CODE REVIEW

**Comment by crawford** [comment]
@marineam is app-admin the appropriate category for Mayday?

**Comment by marineam** [comment]
app-admin sounds good to me

**Comment by marineam** [comment]
LGTM but please rebase and check if the coreos ebuild needs another revision increment

**Comment by mischief** [comment]
ok, i think i did it right. PTAL @marineam

**Comment by marineam** [comment]
Ok, ship it! :)

**Pull request merged**
