### PR TITLE
Adding Integrity Management Architecture (IMA) support to CoreOS

### PR DESCRIPTION
**Pull request by Akhna**
Adding Integrity Management Architecture (IMA) support to CoreOS.

IMA can be used to prevent the execution of unknown binaries or log executed files.

This should not have a performance impact unless IMA is customized with boot options or a custom policy.

Feature request: https://github.com/coreos/bugs/issues/416

### CODE REVIEW

**Comment by mischief** [comment]
hello @Akhna, did you use `make savedefconfig` to make this config?

also, is IMA applicable to arm64 as well (arm64_defconfig-4.1)?

**Comment by marineam** [comment]
I wouldn't bother with arm right now, don't think audit is enabled there
yet. We will sync up arm features later.

**Comment by Akhna** [comment]
Done.

Ran `make savedefconfig`, which removed the unnecessary lines I got from running `make menuconfig` alone.

Leaving out arm64 for now per Michael's comment.

**Comment by Akhna** [comment]
Do you have any concerns about enabling IMA you'd like to discuss?

**Comment by crawford** [comment]
Superseded by https://github.com/coreos/coreos-overlay/pull/2134.

**Pull request closed without merging**
